apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: MONGODB_CONNECTION
          value: mongodb://mongo:27017/contentdb
        image: localhost:5000/content-api
        imagePullPolicy: Never
        name: api
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
