apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -o k8s/
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: CONTENT_API_URL
          value: http://api:3001
        image: localhost:5000/content-web
        imagePullPolicy: Never
        name: web
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
